jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven central repository
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '11'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      name: publish packages
      run: mvn -P ossrhDeploy --batch-mode -DskipTests javadoc:aggregate-jar source:jar
        deploy
name: Snapshot package publisher
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
